### PR TITLE
maya-like infix math form (no order of operations)

### PR DESCRIPTION
**Pull request by AlexKnauth**
see https://github.com/jarcane/heresy/issues/20

### CODE REVIEW

**Comment by jarcane** [comment]
I love the syntax here; especially the addition of the `let` keyword; it feels very idiomatic to BASIC and Heresy both, and I see what you meant now about syntax-classes being a neater way to code in new literals.

I'm a little concerned about the external dependency however. I had kind of hoped to be able to actually implement our own version of the threading macro; it's one more code sample for learners, and adding an external dependency could be a point of friction down the line if and when I decide to implement Heresy as a native interpreter/compiler in the future (something I'm still a bit undecided on, but try to keep in mind).

**Comment by AlexKnauth** [comment]
There is actually no dependancy or rackjure for the implementation of it, but there is for the tests, because I use `let D = b * b - d ~> sqrt`.  For that particular use of it, reimplementing a simple version of it should be no more difficult than `(def macro ~> (a b) (b a))`.

**Comment by AlexKnauth** [comment]
Should we try to support order of operations, or should we just leave it as a purely left-folding thing where `(m 1 + 2 / 3)` expands to `(/ (+ 1 2) 3)` instead of `(+ 1 (/ 2 3))`?

**Comment by jarcane** [comment]
I think it would probably be closer to what a user might expect if it did. I'm rubbish at remembering my order of operations myself though, so I rarely rely on it.

**Comment by AlexKnauth** [comment]
I'm working on a general infix macro that would follow order of operations along with allowing generality and extensibility, but it's not ready right now and I'm not sure how much time I'll have to work on it.  In the mean time I made [this](https://github.com/AlexKnauth/infix-macro/blob/master/infix/infix-macro.rkt) if you're interested, but it is definitely not general or extensible, so the everything other than +, *, -, /, and ^ won't work unless I hard code it in.

**Comment by AlexKnauth** [comment]
Would it make sense to provide one form that would follow order of operations and another more general form that follows a more maya-like left-folding thing without order of operations?  What would these two separate things be called?

**Comment by AlexKnauth** [comment]
Or would it make sense to have a form that follows maya-like rules without order of operations until it sees some special literal which tells it to use order of operations?  Or would this be too confusing?
```
(m a + b / : a ^ 2 + b ^ 2 : ~> sqrt) ; the `:`s tell it to use order of operations between them
;=>
(~> (/ (+ a b) (+ (^ a 2) (^ b 2))) sqrt)
```
Or would it make sense to use curly braces or something like that to mean follow order of operations? (which is possible through syntax-properties)
```
(m a + b / {a ^ 2 + b ^ 2} ~> sqrt) ; the {} tell it to use order of operations
;=>
(~> (/ (+ a b) (+ (^ a 2) (^ b 2))) sqrt)
```
I think I like the curly braces better, but what do you think?  Or would you want to be able to use curly braces for something else?
Or with the two different forms as in the last post:
```
(m a + b / (: a ^ 2 + b ^ 2) ~> sqrt) ; the : is a separate macro that uses order of operations
;=>
(~> (/ (+ a b) (+ (^ a 2) (^ b 2))) sqrt)
```
What do you think of these options?

**Comment by jarcane** [comment]
I think that's likely getting a bit too complicated; really, I'm not sure it's necessary to be able to do one or the other. Rather, I was thinking perhaps that the standard math operators (+,-,etc.) should follow their expected order of operations (PEMDAS I suppose). Any non-standard operator is going to be in parens anyway, and thus automatically of first precedence anyway, and parens themselves can thus also be used to finesse the order of operations as desired just like any other language.

**Comment by AlexKnauth** [comment]
But in a form that follows order of operations, things like `~> sqrt` wouldn't be able to be used in infix or postfix-like notation, so it would have to be `(sqrt (m a + b))`, which isn't as convenient or as general as  something that allows `(m a + b ~> sqrt)`, where neither + nor ~> nor sqrt is built in to the `m` form. I actually like the generality of just following a left-folding postfix style where for any op1 and op2, (m a op1 b op2 c) always expands to `(op2 (op1 a b) c)`, but I also think a form or sub-form that uses order of operations would be a good thing to have when I want it.

**Comment by jarcane** [comment]
What if you took a page from Haskell, and made the `~>` evaluate last and to the right, like a flipped `$` operator? So everything to the left of the ~> would be evaluated first, then the result past to the function to the right.

Then you still get order of operations, while getting the expected behavior.

**Comment by AlexKnauth** [comment]
In my opinion I think that combined with order of operations might be too confusing, but a consistently left-folding thing would make every operation behave like ~>, which does make a lot of sense if you just forget order of operations (but there should also be a way of supporting order of operations in either a different macro or within {} or something).  But if you think it wouldn't be too confusing, then okay.  
Just to check, you mean like this, right?:
```racket
(m a ^ 2 + b ^ 2 ~> sqrt)
```
But then what if you had something like this:
```racket
(m a ^ 2 + b ^ 2 ~> sqrt + a ~> sqrt * b)
```
Then it looks like the + operator has both greater and lesser precedence than the ~> operator, and ideally ~> would not have to be treated specially.  So people (I know I would) might be confused as to whether the above example would expand to
```racket
(+ (sqrt (+ (^ a 2) (^ b 2))) (* (sqrt a) b))
```
Or
```racket
(* (sqrt (+ (sqrt (+ (^ a 2) (^ b 2))) a)) b)
```
But using something like this:
```racket
(m {a ^ 2 + b ^ 2} ~> sqrt + {(sqrt a) * b})
```
Is much less confusing to me if I understand that `m` always does the left-folding postfix thing except within {}.  But again, if you don't think the first two examples would be too confusing, then okay.

**Comment by jarcane** [comment]
OK, so I finally have a little more free time to spare for this, and had a look back over the changes,  and I'm merging this. My absolute sincerest apologies for neglecting this for so long.

**Pull request merged**
