### PR TITLE
add thing macro and add extends syntax

### PR DESCRIPTION
**Pull request by AlexKnauth**
(describe name (field value) …)
(describe name extends super-thing (field value) …)
(thing (field value) …)
(thing extends super-thing (field value) …)

### CODE REVIEW

**Comment by jarcane** [comment]
Am I reading this correctly that you've managed to implement inheritance?

**Comment by AlexKnauth** [comment]
Oh I forgot to mention that (thing extends ...) and (describe name extends ...) can change the order of the fields, which could make the (Santa `(* * empty)) pattern matching do unexpected things.  We might need a helper function that merges the two association lists without changing the order in an unexpected way.

**Comment by AlexKnauth** [comment]
Ok it now keeps the order of the fields the same.

**Comment by jarcane** [comment]
OK, I think I follow this now that there's an example. I like the "extends" keyword for inheritance as well.

Would you mind submitting some documentation to the Scribble file to go along with this before I merge it?

**Comment by jarcane** [comment]
Excellent, thanks for doing this, and my apologies for taking so long to process the pull request.

**Pull request merged**
